// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DenonESPD_v2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
void ui_event_timeLbl(lv_event_t * e);
lv_obj_t * ui_timeLbl;
lv_obj_t * ui_dateLbl;
lv_obj_t * ui_songProgress;
void ui_event_playBtn(lv_event_t * e);
lv_obj_t * ui_playBtn;
void ui_event_stopBtn(lv_event_t * e);
lv_obj_t * ui_stopBtn;
void ui_event_fwBtn(lv_event_t * e);
lv_obj_t * ui_fwBtn;
void ui_event_rwBtn(lv_event_t * e);
lv_obj_t * ui_rwBtn;
lv_obj_t * ui_songLbl;
lv_obj_t * ui_artistLbl;
lv_obj_t * ui_albumLbl;
lv_obj_t * ui_actSongTime;
lv_obj_t * ui_songTime;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label2;
void ui_event_backlitSld(lv_event_t * e);
lv_obj_t * ui_backlitSld;
lv_obj_t * ui_Label3;
void ui_event_calBtn(lv_event_t * e);
lv_obj_t * ui_calBtn;
lv_obj_t * ui_calLbl;
void ui_event_backBtn(lv_event_t * e);
lv_obj_t * ui_backBtn;
lv_obj_t * ui_saveBack;
void ui_event_timeLbl2(lv_event_t * e);
lv_obj_t * ui_timeLbl2;
void ui_event_heosSetupBtn(lv_event_t * e);
lv_obj_t * ui_heosSetupBtn;
lv_obj_t * ui_heosSetupLbl;
void ui_event_rebootBtn(lv_event_t * e);
lv_obj_t * ui_rebootBtn;
lv_obj_t * ui_rebootLbl;
void ui_event_WiFiSetupBtn1(lv_event_t * e);
lv_obj_t * ui_WiFiSetupBtn1;
lv_obj_t * ui_WiFiSetupLbl1;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_TabView3;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_bootLbl;
lv_obj_t * ui_sdLbl;
lv_obj_t * ui_wifLoadLbl;
lv_obj_t * ui_wifConLbl;
lv_obj_t * ui_heosLbl;
lv_obj_t * ui_calLoadLbl;
lv_obj_t * ui_settingsLoadLbl;
// CUSTOM VARIABLES


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_TabView4;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_bootLbl1;
void ui_event_scanWifi(lv_event_t * e);
lv_obj_t * ui_scanWifi;
lv_obj_t * ui_scanLbl;
lv_obj_t * ui_passTxtbox;
lv_obj_t * ui_ssidDrop;
lv_obj_t * ui_Keyboard1;
void ui_event_connectBtn(lv_event_t * e);
lv_obj_t * ui_connectBtn;
lv_obj_t * ui_connectLbl;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenReboot
void ui_ScreenReboot_screen_init(void);
lv_obj_t * ui_ScreenReboot;
lv_obj_t * ui_TabView5;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_bootLbl2;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label10;
// CUSTOM VARIABLES


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_TabView6;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Lbl3;
void ui_event_saveHeosBtn(lv_event_t * e);
lv_obj_t * ui_saveHeosBtn;
lv_obj_t * ui_saveHeosLbl1;
lv_obj_t * ui_heosIPTxt;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_timeLbl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hiddenServiceMenu(e);
    }
}

void ui_event_playBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        playBtnDen(e);
    }
}

void ui_event_stopBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        stopBtnDen(e);
    }
}

void ui_event_fwBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fwBtnDen(e);
    }
}

void ui_event_rwBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        rwBtnDen(e);
    }
}

void ui_event_backlitSld(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lcdSetBacklight(e);
    }
}

void ui_event_calBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calDisplay(e);
    }
}

void ui_event_backBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveBackMain(e);
    }
}

void ui_event_timeLbl2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hiddenServiceMenu(e);
    }
}

void ui_event_heosSetupBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        heosSetup(e);
    }
}

void ui_event_rebootBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        rbtSetting(e);
    }
}

void ui_event_WiFiSetupBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifiSetup(e);
    }
}

void ui_event_scanWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scanWifi(e);
    }
}

void ui_event_connectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connWifi(e);
    }
}

void ui_event_saveHeosBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        heosSave(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_ScreenReboot_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
