// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DenonESPD_v2

#ifndef _DENONESPD_V2_UI_H
#define _DENONESPD_V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
void ui_event_timeLbl(lv_event_t * e);
extern lv_obj_t * ui_timeLbl;
extern lv_obj_t * ui_dateLbl;
extern lv_obj_t * ui_songProgress;
void ui_event_playBtn(lv_event_t * e);
extern lv_obj_t * ui_playBtn;
void ui_event_stopBtn(lv_event_t * e);
extern lv_obj_t * ui_stopBtn;
void ui_event_fwBtn(lv_event_t * e);
extern lv_obj_t * ui_fwBtn;
void ui_event_rwBtn(lv_event_t * e);
extern lv_obj_t * ui_rwBtn;
extern lv_obj_t * ui_songLbl;
extern lv_obj_t * ui_artistLbl;
extern lv_obj_t * ui_albumLbl;
extern lv_obj_t * ui_actSongTime;
extern lv_obj_t * ui_songTime;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
void ui_event_backlitSld(lv_event_t * e);
extern lv_obj_t * ui_backlitSld;
extern lv_obj_t * ui_Label3;
void ui_event_calBtn(lv_event_t * e);
extern lv_obj_t * ui_calBtn;
extern lv_obj_t * ui_calLbl;
void ui_event_backBtn(lv_event_t * e);
extern lv_obj_t * ui_backBtn;
extern lv_obj_t * ui_saveBack;
void ui_event_timeLbl2(lv_event_t * e);
extern lv_obj_t * ui_timeLbl2;
void ui_event_heosSetupBtn(lv_event_t * e);
extern lv_obj_t * ui_heosSetupBtn;
extern lv_obj_t * ui_heosSetupLbl;
void ui_event_rebootBtn(lv_event_t * e);
extern lv_obj_t * ui_rebootBtn;
extern lv_obj_t * ui_rebootLbl;
void ui_event_WiFiSetupBtn1(lv_event_t * e);
extern lv_obj_t * ui_WiFiSetupBtn1;
extern lv_obj_t * ui_WiFiSetupLbl1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_bootLbl;
extern lv_obj_t * ui_sdLbl;
extern lv_obj_t * ui_wifLoadLbl;
extern lv_obj_t * ui_wifConLbl;
extern lv_obj_t * ui_heosLbl;
extern lv_obj_t * ui_calLoadLbl;
extern lv_obj_t * ui_settingsLoadLbl;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_TabView4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_bootLbl1;
void ui_event_scanWifi(lv_event_t * e);
extern lv_obj_t * ui_scanWifi;
extern lv_obj_t * ui_scanLbl;
extern lv_obj_t * ui_passTxtbox;
extern lv_obj_t * ui_ssidDrop;
extern lv_obj_t * ui_Keyboard1;
void ui_event_connectBtn(lv_event_t * e);
extern lv_obj_t * ui_connectBtn;
extern lv_obj_t * ui_connectLbl;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenReboot
void ui_ScreenReboot_screen_init(void);
extern lv_obj_t * ui_ScreenReboot;
extern lv_obj_t * ui_TabView5;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_bootLbl2;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_TabView6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Lbl3;
void ui_event_saveHeosBtn(lv_event_t * e);
extern lv_obj_t * ui_saveHeosBtn;
extern lv_obj_t * ui_saveHeosLbl1;
extern lv_obj_t * ui_heosIPTxt;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_playico_sm_png);    // assets/playIco_sm.png
LV_IMG_DECLARE(ui_img_stopico_sm_png);    // assets/stopIco_sm.png
LV_IMG_DECLARE(ui_img_fwico_sm_png);    // assets/fwIco_sm.png
LV_IMG_DECLARE(ui_img_rwico_sm_png);    // assets/rwIco_sm.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
