// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DenonESPD

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView6 = lv_tabview_create(ui_Screen5);
    lv_tabview_set_tab_bar_size(ui_TabView6, 25);
    lv_obj_set_width(ui_TabView6, 320);
    lv_obj_set_height(ui_TabView6, 240);
    lv_obj_set_align(ui_TabView6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView6), lv_color_hex(0x66676A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView6), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_bar(ui_TabView6), lv_color_hex(0x19171A),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(lv_tabview_get_tab_bar(ui_TabView6), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(lv_tabview_get_tab_bar(ui_TabView6), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_bar(ui_TabView6), LV_GRAD_DIR_VER,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel5, 320);
    lv_obj_set_height(ui_Panel5, 83);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, -50);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lbl3 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Lbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lbl3, 0);
    lv_obj_set_y(ui_Lbl3, 3);
    lv_obj_set_align(ui_Lbl3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Lbl3, "HEOS Setup");

    ui_saveHeosBtn = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_saveHeosBtn, 65);
    lv_obj_set_height(ui_saveHeosBtn, 34);
    lv_obj_set_x(ui_saveHeosBtn, 86);
    lv_obj_set_y(ui_saveHeosBtn, -45);
    lv_obj_set_align(ui_saveHeosBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saveHeosBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_saveHeosBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_saveHeosBtn, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveHeosBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_saveHeosBtn, lv_color_hex(0x595500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_saveHeosBtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveHeosLbl1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_saveHeosLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveHeosLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_saveHeosLbl1, 87);
    lv_obj_set_y(ui_saveHeosLbl1, -47);
    lv_obj_set_align(ui_saveHeosLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saveHeosLbl1, "Save");
    lv_obj_set_style_text_color(ui_saveHeosLbl1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_saveHeosLbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heosIPTxt = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_heosIPTxt, 160);
    lv_obj_set_height(ui_heosIPTxt, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_heosIPTxt, 13);
    lv_obj_set_y(ui_heosIPTxt, -44);
    lv_obj_set_align(ui_heosIPTxt, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_heosIPTxt, 15);
    lv_textarea_set_placeholder_text(ui_heosIPTxt, "IP");
    lv_textarea_set_one_line(ui_heosIPTxt, true);



    ui_Keyboard2 = lv_keyboard_create(ui_Screen5);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 312);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 56);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_Label14 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -110);
    lv_obj_set_y(ui_Label14, -77);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "HEOS IP");

    lv_obj_add_event_cb(ui_saveHeosBtn, ui_event_saveHeosBtn, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_heosIPTxt);

}
