// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DenonESPD_v2

#include "ui.h"

void ui_ScreenReboot_screen_init(void)
{
    ui_ScreenReboot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenReboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView5 = lv_tabview_create(ui_ScreenReboot);
    lv_tabview_set_tab_bar_size(ui_TabView5, 25);
    lv_obj_set_width(ui_TabView5, 320);
    lv_obj_set_height(ui_TabView5, 240);
    lv_obj_set_align(ui_TabView5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView5), lv_color_hex(0x66676A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView5), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_bar(ui_TabView5), lv_color_hex(0x19171A),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(lv_tabview_get_tab_bar(ui_TabView5), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(lv_tabview_get_tab_bar(ui_TabView5), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_bar(ui_TabView5), LV_GRAD_DIR_VER,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_ScreenReboot);
    lv_obj_set_width(ui_Panel4, 320);
    lv_obj_set_height(ui_Panel4, 122);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 4);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bootLbl2 = lv_label_create(ui_ScreenReboot);
    lv_obj_set_width(ui_bootLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bootLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bootLbl2, 0);
    lv_obj_set_y(ui_bootLbl2, 4);
    lv_obj_set_align(ui_bootLbl2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_bootLbl2, "Rebooting");

    ui_Spinner1 = lv_spinner_create(ui_ScreenReboot);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 57);
    lv_obj_set_height(ui_Spinner1, 67);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 31);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ScreenReboot);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -1);
    lv_obj_set_y(ui_Label10, -32);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "PLEASE WAIT...");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);


}
