// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DenonESPD_v2

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView2 = lv_tabview_create(ui_Screen2);
    lv_tabview_set_tab_bar_size(ui_TabView2, 25);
    lv_obj_set_width(ui_TabView2, 320);
    lv_obj_set_height(ui_TabView2, 240);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0x66676A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0x19171A),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(lv_tabview_get_tab_bar(ui_TabView2), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(lv_tabview_get_tab_bar(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_bar(ui_TabView2), LV_GRAD_DIR_VER,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 320);
    lv_obj_set_height(ui_Panel2, 136);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 6);
    lv_obj_set_y(ui_Label2, 1);
    lv_label_set_text(ui_Label2, "Settings");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backlitSld = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_backlitSld, 10, 255);
    lv_slider_set_value(ui_backlitSld, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_backlitSld) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_backlitSld, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_backlitSld, 150);
    lv_obj_set_height(ui_backlitSld, 10);
    lv_obj_set_x(ui_backlitSld, 66);
    lv_obj_set_y(ui_backlitSld, -48);
    lv_obj_set_align(ui_backlitSld, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backlitSld, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backlitSld, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_backlitSld, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_backlitSld, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_backlitSld, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_backlitSld, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_backlitSld, lv_color_hex(0xFFD300), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backlitSld, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_backlitSld, lv_color_hex(0xFEFF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backlitSld, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_backlitSld, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_backlitSld,
                                                                                                 lv_obj_get_style_pad_right(ui_backlitSld, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -103);
    lv_obj_set_y(ui_Label3, -49);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Backlight :");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFEFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calBtn = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_calBtn, 90);
    lv_obj_set_height(ui_calBtn, 30);
    lv_obj_set_x(ui_calBtn, -104);
    lv_obj_set_y(ui_calBtn, 39);
    lv_obj_set_align(ui_calBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_calBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_calBtn, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_calBtn, lv_color_hex(0x595500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_calBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_calBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_calBtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_calBtn, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calLbl = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_calLbl, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_calLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_calLbl, -104);
    lv_obj_set_y(ui_calLbl, 39);
    lv_obj_set_align(ui_calLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calLbl, "Calibrate");
    lv_obj_set_style_text_color(ui_calLbl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backBtn = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_backBtn, 77);
    lv_obj_set_height(ui_backBtn, 30);
    lv_obj_set_x(ui_backBtn, 108);
    lv_obj_set_y(ui_backBtn, 94);
    lv_obj_set_align(ui_backBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backBtn, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_backBtn, lv_color_hex(0x595500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_backBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_backBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_backBtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_backBtn, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveBack = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_saveBack, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_saveBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_saveBack, 109);
    lv_obj_set_y(ui_saveBack, 94);
    lv_obj_set_align(ui_saveBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saveBack, "Back");
    lv_obj_set_style_text_color(ui_saveBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_saveBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLbl2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_timeLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLbl2, 123);
    lv_obj_set_y(ui_timeLbl2, -109);
    lv_obj_set_align(ui_timeLbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLbl2, "00:00:00");
    lv_obj_add_flag(ui_timeLbl2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_timeLbl2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heosSetupBtn = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_heosSetupBtn, 90);
    lv_obj_set_height(ui_heosSetupBtn, 30);
    lv_obj_set_x(ui_heosSetupBtn, 0);
    lv_obj_set_y(ui_heosSetupBtn, 39);
    lv_obj_set_align(ui_heosSetupBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heosSetupBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_heosSetupBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_heosSetupBtn, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heosSetupBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_heosSetupBtn, lv_color_hex(0x595500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_heosSetupBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_heosSetupBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_heosSetupBtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_heosSetupBtn, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heosSetupBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heosSetupLbl = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_heosSetupLbl, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_heosSetupLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heosSetupLbl, -1);
    lv_obj_set_y(ui_heosSetupLbl, 38);
    lv_obj_set_align(ui_heosSetupLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heosSetupLbl, "HEOS Setup");
    lv_obj_set_style_text_color(ui_heosSetupLbl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heosSetupLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rebootBtn = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_rebootBtn, 77);
    lv_obj_set_height(ui_rebootBtn, 30);
    lv_obj_set_x(ui_rebootBtn, -106);
    lv_obj_set_y(ui_rebootBtn, 94);
    lv_obj_set_align(ui_rebootBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rebootBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_rebootBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rebootBtn, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rebootBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rebootBtn, lv_color_hex(0x595500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_rebootBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rebootBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_rebootBtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_rebootBtn, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rebootBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rebootLbl = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_rebootLbl, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_rebootLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rebootLbl, -107);
    lv_obj_set_y(ui_rebootLbl, 94);
    lv_obj_set_align(ui_rebootLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rebootLbl, "Reboot");
    lv_obj_set_style_text_color(ui_rebootLbl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rebootLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiSetupBtn1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_WiFiSetupBtn1, 90);
    lv_obj_set_height(ui_WiFiSetupBtn1, 30);
    lv_obj_set_x(ui_WiFiSetupBtn1, 103);
    lv_obj_set_y(ui_WiFiSetupBtn1, 39);
    lv_obj_set_align(ui_WiFiSetupBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiSetupBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WiFiSetupBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiSetupBtn1, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiSetupBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WiFiSetupBtn1, lv_color_hex(0x595500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_WiFiSetupBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_WiFiSetupBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WiFiSetupBtn1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WiFiSetupBtn1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiSetupBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiSetupLbl1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_WiFiSetupLbl1, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_WiFiSetupLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiSetupLbl1, 103);
    lv_obj_set_y(ui_WiFiSetupLbl1, 39);
    lv_obj_set_align(ui_WiFiSetupLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiSetupLbl1, "WiFi Setup");
    lv_obj_set_style_text_color(ui_WiFiSetupLbl1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiSetupLbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backlitSld, ui_event_backlitSld, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calBtn, ui_event_calBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backBtn, ui_event_backBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeLbl2, ui_event_timeLbl2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_heosSetupBtn, ui_event_heosSetupBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rebootBtn, ui_event_rebootBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiSetupBtn1, ui_event_WiFiSetupBtn1, LV_EVENT_ALL, NULL);

}
