// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DenonESPD_v2

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1);
    lv_tabview_set_tab_bar_size(ui_TabView1, 20);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 240);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x757575),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x1E1B23),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_bar(ui_TabView1), LV_GRAD_DIR_VER,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_bar(ui_TabView1), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_bar(ui_TabView1), LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLbl, 123);
    lv_obj_set_y(ui_timeLbl, -109);
    lv_obj_set_align(ui_timeLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLbl, "00:00:00");
    lv_obj_add_flag(ui_timeLbl, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_timeLbl, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_dateLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateLbl, -107);
    lv_obj_set_y(ui_dateLbl, -109);
    lv_obj_set_align(ui_dateLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateLbl, "23/11/2024");
    lv_obj_add_flag(ui_dateLbl, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_dateLbl, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songProgress = lv_bar_create(ui_Screen1);
    lv_obj_set_width(ui_songProgress, 285);
    lv_obj_set_height(ui_songProgress, 10);
    lv_obj_set_x(ui_songProgress, 1);
    lv_obj_set_y(ui_songProgress, 45);
    lv_obj_set_align(ui_songProgress, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_songProgress, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_songProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_songProgress, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_songProgress, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_songProgress, lv_color_hex(0xBCBCBC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_songProgress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_songProgress, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_songProgress,
                                                                                                   lv_obj_get_style_pad_right(ui_songProgress, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_playBtn = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_playBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_playico_sm_png, NULL);
    lv_obj_set_width(ui_playBtn, 25);
    lv_obj_set_height(ui_playBtn, 25);
    lv_obj_set_x(ui_playBtn, -36);
    lv_obj_set_y(ui_playBtn, 78);
    lv_obj_set_align(ui_playBtn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_playBtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_playBtn, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_transform_scale(ui_playBtn, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stopBtn = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_stopBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_stopico_sm_png, NULL);
    lv_obj_set_height(ui_stopBtn, 25);
    lv_obj_set_width(ui_stopBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_stopBtn, 25);
    lv_obj_set_y(ui_stopBtn, 78);
    lv_obj_set_align(ui_stopBtn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_stopBtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_transform_scale(ui_stopBtn, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwBtn = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_fwBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_fwico_sm_png, NULL);
    lv_obj_set_height(ui_fwBtn, 25);
    lv_obj_set_width(ui_fwBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_fwBtn, 87);
    lv_obj_set_y(ui_fwBtn, 78);
    lv_obj_set_align(ui_fwBtn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_fwBtn, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_transform_scale(ui_fwBtn, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rwBtn = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_rwBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_rwico_sm_png, NULL);
    lv_obj_set_height(ui_rwBtn, 25);
    lv_obj_set_width(ui_rwBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rwBtn, -98);
    lv_obj_set_y(ui_rwBtn, 78);
    lv_obj_set_align(ui_rwBtn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rwBtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_transform_scale(ui_rwBtn, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_songLbl, 275);
    lv_obj_set_height(ui_songLbl, 20);
    lv_obj_set_x(ui_songLbl, 21);
    lv_obj_set_y(ui_songLbl, -68);
    lv_obj_set_align(ui_songLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_songLbl, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_songLbl, "N/A");
    lv_obj_set_style_text_color(ui_songLbl, lv_color_hex(0xFEFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_songLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_songLbl, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_artistLbl, 275);
    lv_obj_set_height(ui_artistLbl, 20);
    lv_obj_set_x(ui_artistLbl, 21);
    lv_obj_set_y(ui_artistLbl, -40);
    lv_obj_set_align(ui_artistLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_artistLbl, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_artistLbl, "N/A");
    lv_obj_set_style_text_color(ui_artistLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_artistLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_artistLbl, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_albumLbl, 275);
    lv_obj_set_height(ui_albumLbl, 20);
    lv_obj_set_x(ui_albumLbl, 21);
    lv_obj_set_y(ui_albumLbl, -13);
    lv_obj_set_align(ui_albumLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_albumLbl, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_albumLbl, "N/A");
    lv_obj_set_style_text_color(ui_albumLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_albumLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_albumLbl, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actSongTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_actSongTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_actSongTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_actSongTime, -124);
    lv_obj_set_y(ui_actSongTime, 25);
    lv_obj_set_align(ui_actSongTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_actSongTime, "00:00");
    lv_obj_set_style_text_font(ui_actSongTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_songTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_songTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_songTime, 126);
    lv_obj_set_y(ui_songTime, 26);
    lv_obj_set_align(ui_songTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_songTime, "00:00");
    lv_obj_set_style_text_font(ui_songTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_timeLbl, ui_event_timeLbl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_playBtn, ui_event_playBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopBtn, ui_event_stopBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fwBtn, ui_event_fwBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rwBtn, ui_event_rwBtn, LV_EVENT_ALL, NULL);

}
