// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DenonESPD

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void hiddenServiceMenu(lv_event_t * e);
void playBtnDen(lv_event_t * e);
void stopBtnDen(lv_event_t * e);
void fwBtnDen(lv_event_t * e);
void rwBtnDen(lv_event_t * e);
void lcdSetBacklight(lv_event_t * e);
void calDisplay(lv_event_t * e);
void saveBackMain(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
